name: CI

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: JustinBeckwith/linkinator-action@v1
        name: Lint links
        with:
          paths: 'https://logchimp.codecarrot.net/'
          recurse: true
          linksToSkip: 'https://render.com, https://m.do.co, https://github.com, https://www.postgresql.org, https://opencollective.com, https://gitpod.io, https://www.keycdn.com, https://www.browserstack.com, https://hub.docker.com, https://nodejs.org,  https://discordapp.com,  https://www.patreon.com, https://twitter.com, https://js.stripe.com/v3, https://www.macstadium.com, https://discord.gg, https://yarnpkg.com, https://www.codecarrot.net, https://railway.app, https://docs.railway.app'
