name: Linkinator

on:
  push:
    branches:
      - v0-2
  pull_request:
    branches:
      - v0-2
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v5

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Run Linkinator
      - name: Lint Links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: 'https://docs.logchimp.codecarrot.net/'
          recurse: true
          linksToSkip: '^https?://(?!docs\.logchimp\.codecarrot\.net).*'
